name: '22'
timestamp: 1529397039
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1529395549
positions:
  header-c: header-c
  drawer: Drawer
  drawer-a: Drawer-A
  drawer-b: Drawer-B
  content-top-1a: 'Module Position'
  content-top-1b: 'Module Position'
  content-top-2: 'Module Position'
  content-top-2a: 'Module Position'
  content-top-2b: 'Module Position'
  content-top-2c: 'Module Position'
  testimonials-a: 'Module Position'
  testimonials-b: 'Module Position'
  testimonials: 'Module Position'
  aside: Aside
  sidebar: Sidebar
  bottom-a: 'Module Position'
  bottom-b: 'Module Position'
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  spacer:
    spacer-spacer-9107: Spacer
    spacer-spacer-9310: Spacer
  module:
    position-module-5472: 'Logog HESAM'
    position-module-5514: 'Top links'
    position-module-4561: 'logo 1000 doc'
    position-module-1599: 'coord menu'
  social:
    social-3171: Social
  menu:
    menu-8075: Menu
  position:
    position-position-4649: header-c
    position-position-5397: Drawer
    position-position-5285: Drawer-A
    position-position-2450: Drawer-B
    position-position-3731: 'Module Position'
    position-position-1290: 'Module Position'
    position-position-6169: 'Module Position'
    position-position-3740: 'Module Position'
    position-position-3166: 'Module Position'
    position-position-5511: 'Module Position'
    position-position-2587: 'Module Position'
    position-position-9141: 'Module Position'
    position-position-8508: 'Module Position'
    position-position-4734: Aside
    position-position-3949: Sidebar
    position-position-5043: 'Module Position'
    position-position-3615: 'Module Position'
  content:
    system-content-1587: 'Page Content'
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  copyright:
    copyright-3869: Copyright
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
