name: '24'
timestamp: 1529395549
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1529395549
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7972: 'System Messages'
    system-messages-9333: 'System Messages'
  logo:
    logo-9608: 'Logo / Image'
    logo-9571: 'Logo / Image'
    logo-2291: 'Logo / Image'
    logo-4603: 'Logo / Image'
  menu:
    menu-6409: Menu
    menu-1539: Menu
  social:
    social-3171: Social
    social-2472: Social
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
    position-position-7797: Aside
    position-position-2076: Sidebar
  content:
    system-content-1587: 'Page Content'
    system-content-2241: 'Page Content'
  copyright:
    copyright-1736: Copyright
    copyright-2745: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
    horizontalmenu-4896: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
    totop-7169: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
    mobile-menu-2042: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-7972: system-messages-7972
    logo-9608: logo-9608
    menu-6409: menu-6409
    social-3171: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    position-position-4734: position-position-4734
    mainbar: mainbar
    system-content-1587: system-content-1587
    sidebar: sidebar
    position-position-3949: position-position-3949
    footer: footer
    logo-9571: logo-9571
    copyright-1736: copyright-1736
    horizontalmenu-9034: horizontalmenu-9034
    totop-8670: totop-8670
    offcanvas: offcanvas
    mobile-menu-5697: mobile-menu-5697
    system-messages-9333: system-messages-7972
    logo-2291: logo-9608
    menu-1539: menu-6409
    social-2472: social-3171
    position-position-7797: position-position-4734
    system-content-2241: system-content-1587
    position-position-2076: position-position-3949
    logo-4603: logo-9571
    copyright-2745: copyright-1736
    horizontalmenu-4896: horizontalmenu-9034
    totop-7169: totop-8670
    mobile-menu-2042: mobile-menu-5697
